# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _dcparser
else:
    import _dcparser

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _dcparser.delete_SwigPyIterator

    def value(self):
        return _dcparser.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _dcparser.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _dcparser.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _dcparser.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _dcparser.SwigPyIterator_equal(self, x)

    def copy(self):
        return _dcparser.SwigPyIterator_copy(self)

    def next(self):
        return _dcparser.SwigPyIterator_next(self)

    def __next__(self):
        return _dcparser.SwigPyIterator___next__(self)

    def previous(self):
        return _dcparser.SwigPyIterator_previous(self)

    def advance(self, n):
        return _dcparser.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _dcparser.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _dcparser.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _dcparser.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _dcparser.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _dcparser.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _dcparser.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _dcparser:
_dcparser.SwigPyIterator_swigregister(SwigPyIterator)

class vector_uchar(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _dcparser.vector_uchar_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _dcparser.vector_uchar___nonzero__(self)

    def __bool__(self):
        return _dcparser.vector_uchar___bool__(self)

    def __len__(self):
        return _dcparser.vector_uchar___len__(self)

    def __getslice__(self, i, j):
        return _dcparser.vector_uchar___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _dcparser.vector_uchar___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _dcparser.vector_uchar___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _dcparser.vector_uchar___delitem__(self, *args)

    def __getitem__(self, *args):
        return _dcparser.vector_uchar___getitem__(self, *args)

    def __setitem__(self, *args):
        return _dcparser.vector_uchar___setitem__(self, *args)

    def pop(self):
        return _dcparser.vector_uchar_pop(self)

    def append(self, x):
        return _dcparser.vector_uchar_append(self, x)

    def empty(self):
        return _dcparser.vector_uchar_empty(self)

    def size(self):
        return _dcparser.vector_uchar_size(self)

    def swap(self, v):
        return _dcparser.vector_uchar_swap(self, v)

    def begin(self):
        return _dcparser.vector_uchar_begin(self)

    def end(self):
        return _dcparser.vector_uchar_end(self)

    def rbegin(self):
        return _dcparser.vector_uchar_rbegin(self)

    def rend(self):
        return _dcparser.vector_uchar_rend(self)

    def clear(self):
        return _dcparser.vector_uchar_clear(self)

    def get_allocator(self):
        return _dcparser.vector_uchar_get_allocator(self)

    def pop_back(self):
        return _dcparser.vector_uchar_pop_back(self)

    def erase(self, *args):
        return _dcparser.vector_uchar_erase(self, *args)

    def __init__(self, *args):
        _dcparser.vector_uchar_swiginit(self, _dcparser.new_vector_uchar(*args))

    def push_back(self, x):
        return _dcparser.vector_uchar_push_back(self, x)

    def front(self):
        return _dcparser.vector_uchar_front(self)

    def back(self):
        return _dcparser.vector_uchar_back(self)

    def assign(self, n, x):
        return _dcparser.vector_uchar_assign(self, n, x)

    def resize(self, *args):
        return _dcparser.vector_uchar_resize(self, *args)

    def insert(self, *args):
        return _dcparser.vector_uchar_insert(self, *args)

    def reserve(self, n):
        return _dcparser.vector_uchar_reserve(self, n)

    def capacity(self):
        return _dcparser.vector_uchar_capacity(self)
    __swig_destroy__ = _dcparser.delete_vector_uchar

# Register vector_uchar in _dcparser:
_dcparser.vector_uchar_swigregister(vector_uchar)

class DCDeclaration(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _dcparser.delete_DCDeclaration

    def as_class(self, *args):
        return _dcparser.DCDeclaration_as_class(self, *args)

    def as_switch(self, *args):
        return _dcparser.DCDeclaration_as_switch(self, *args)

    def output(self, *args):
        return _dcparser.DCDeclaration_output(self, *args)

    def write(self, *args):
        return _dcparser.DCDeclaration_write(self, *args)

# Register DCDeclaration in _dcparser:
_dcparser.DCDeclaration_swigregister(DCDeclaration)

class DCClass(DCDeclaration):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, dc_file, name, is_struct, bogus_class):
        _dcparser.DCClass_swiginit(self, _dcparser.new_DCClass(dc_file, name, is_struct, bogus_class))
    __swig_destroy__ = _dcparser.delete_DCClass

    def as_class(self, *args):
        return _dcparser.DCClass_as_class(self, *args)

    def get_dc_file(self):
        return _dcparser.DCClass_get_dc_file(self)

    def get_name(self):
        return _dcparser.DCClass_get_name(self)

    def get_number(self):
        return _dcparser.DCClass_get_number(self)

    def get_num_parents(self):
        return _dcparser.DCClass_get_num_parents(self)

    def get_parent(self, n):
        return _dcparser.DCClass_get_parent(self, n)

    def has_constructor(self):
        return _dcparser.DCClass_has_constructor(self)

    def get_constructor(self):
        return _dcparser.DCClass_get_constructor(self)

    def get_num_fields(self):
        return _dcparser.DCClass_get_num_fields(self)

    def get_field(self, n):
        return _dcparser.DCClass_get_field(self, n)

    def get_field_by_name(self, name):
        return _dcparser.DCClass_get_field_by_name(self, name)

    def get_field_by_index(self, index_number):
        return _dcparser.DCClass_get_field_by_index(self, index_number)

    def get_num_inherited_fields(self):
        return _dcparser.DCClass_get_num_inherited_fields(self)

    def get_inherited_field(self, n):
        return _dcparser.DCClass_get_inherited_field(self, n)

    def is_struct(self):
        return _dcparser.DCClass_is_struct(self)

    def is_bogus_class(self):
        return _dcparser.DCClass_is_bogus_class(self)

    def inherits_from_bogus_class(self):
        return _dcparser.DCClass_inherits_from_bogus_class(self)

    def start_generate(self):
        return _dcparser.DCClass_start_generate(self)

    def stop_generate(self):
        return _dcparser.DCClass_stop_generate(self)

    def output(self, *args):
        return _dcparser.DCClass_output(self, *args)

    def write(self, out, brief, indent_level):
        return _dcparser.DCClass_write(self, out, brief, indent_level)

    def output_instance(self, out, brief, prename, name, postname):
        return _dcparser.DCClass_output_instance(self, out, brief, prename, name, postname)

    def generate_hash(self, hashgen):
        return _dcparser.DCClass_generate_hash(self, hashgen)

    def clear_inherited_fields(self):
        return _dcparser.DCClass_clear_inherited_fields(self)

    def rebuild_inherited_fields(self):
        return _dcparser.DCClass_rebuild_inherited_fields(self)

    def add_field(self, field):
        return _dcparser.DCClass_add_field(self, field)

    def add_parent(self, parent):
        return _dcparser.DCClass_add_parent(self, parent)

    def set_number(self, number):
        return _dcparser.DCClass_set_number(self, number)

# Register DCClass in _dcparser:
_dcparser.DCClass_swigregister(DCClass)
cvar = _dcparser.cvar
dc_multiple_inheritance = cvar.dc_multiple_inheritance
dc_virtual_inheritance = cvar.dc_virtual_inheritance
dc_sort_inheritance_by_file = cvar.dc_sort_inheritance_by_file

class DCKeyword(DCDeclaration):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _dcparser.DCKeyword_swiginit(self, _dcparser.new_DCKeyword(*args))
    __swig_destroy__ = _dcparser.delete_DCKeyword

    def get_name(self):
        return _dcparser.DCKeyword_get_name(self)

    def get_historical_flag(self):
        return _dcparser.DCKeyword_get_historical_flag(self)

    def clear_historical_flag(self):
        return _dcparser.DCKeyword_clear_historical_flag(self)

    def output(self, out, brief):
        return _dcparser.DCKeyword_output(self, out, brief)

    def write(self, out, brief, indent_level):
        return _dcparser.DCKeyword_write(self, out, brief, indent_level)

    def generate_hash(self, hashgen):
        return _dcparser.DCKeyword_generate_hash(self, hashgen)

# Register DCKeyword in _dcparser:
_dcparser.DCKeyword_swigregister(DCKeyword)

class DCKeywordList(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _dcparser.DCKeywordList_swiginit(self, _dcparser.new_DCKeywordList(*args))
    __swig_destroy__ = _dcparser.delete_DCKeywordList

    def has_keyword(self, *args):
        return _dcparser.DCKeywordList_has_keyword(self, *args)

    def get_num_keywords(self):
        return _dcparser.DCKeywordList_get_num_keywords(self)

    def get_keyword(self, n):
        return _dcparser.DCKeywordList_get_keyword(self, n)

    def get_keyword_by_name(self, name):
        return _dcparser.DCKeywordList_get_keyword_by_name(self, name)

    def compare_keywords(self, other):
        return _dcparser.DCKeywordList_compare_keywords(self, other)

    def copy_keywords(self, other):
        return _dcparser.DCKeywordList_copy_keywords(self, other)

    def add_keyword(self, keyword):
        return _dcparser.DCKeywordList_add_keyword(self, keyword)

    def clear_keywords(self):
        return _dcparser.DCKeywordList_clear_keywords(self)

    def output_keywords(self, out):
        return _dcparser.DCKeywordList_output_keywords(self, out)

    def generate_hash(self, hashgen):
        return _dcparser.DCKeywordList_generate_hash(self, hashgen)

# Register DCKeywordList in _dcparser:
_dcparser.DCKeywordList_swigregister(DCKeywordList)

class DCPackData(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _dcparser.DCPackData_swiginit(self, _dcparser.new_DCPackData())
    __swig_destroy__ = _dcparser.delete_DCPackData

    def clear(self):
        return _dcparser.DCPackData_clear(self)

    def append_data(self, buffer, size):
        return _dcparser.DCPackData_append_data(self, buffer, size)

    def get_write_pointer(self, size):
        return _dcparser.DCPackData_get_write_pointer(self, size)

    def append_junk(self, size):
        return _dcparser.DCPackData_append_junk(self, size)

    def rewrite_data(self, position, buffer, size):
        return _dcparser.DCPackData_rewrite_data(self, position, buffer, size)

    def get_rewrite_pointer(self, position, size):
        return _dcparser.DCPackData_get_rewrite_pointer(self, position, size)

    def get_string(self):
        return _dcparser.DCPackData_get_string(self)

    def get_length(self):
        return _dcparser.DCPackData_get_length(self)

    def get_data(self):
        return _dcparser.DCPackData_get_data(self)

    def take_data(self):
        return _dcparser.DCPackData_take_data(self)

# Register DCPackData in _dcparser:
_dcparser.DCPackData_swigregister(DCPackData)

class DCPacker(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _dcparser.DCPacker_swiginit(self, _dcparser.new_DCPacker())
    __swig_destroy__ = _dcparser.delete_DCPacker

    def clear_data(self):
        return _dcparser.DCPacker_clear_data(self)

    def begin_pack(self, root):
        return _dcparser.DCPacker_begin_pack(self, root)

    def end_pack(self):
        return _dcparser.DCPacker_end_pack(self)

    def set_unpack_data(self, *args):
        return _dcparser.DCPacker_set_unpack_data(self, *args)

    def begin_unpack(self, root):
        return _dcparser.DCPacker_begin_unpack(self, root)

    def end_unpack(self):
        return _dcparser.DCPacker_end_unpack(self)

    def begin_repack(self, root):
        return _dcparser.DCPacker_begin_repack(self, root)

    def end_repack(self):
        return _dcparser.DCPacker_end_repack(self)

    def seek(self, *args):
        return _dcparser.DCPacker_seek(self, *args)

    def has_nested_fields(self):
        return _dcparser.DCPacker_has_nested_fields(self)

    def get_num_nested_fields(self):
        return _dcparser.DCPacker_get_num_nested_fields(self)

    def more_nested_fields(self):
        return _dcparser.DCPacker_more_nested_fields(self)

    def get_current_parent(self):
        return _dcparser.DCPacker_get_current_parent(self)

    def get_current_field(self):
        return _dcparser.DCPacker_get_current_field(self)

    def get_last_switch(self):
        return _dcparser.DCPacker_get_last_switch(self)

    def get_pack_type(self):
        return _dcparser.DCPacker_get_pack_type(self)

    def get_current_field_name(self):
        return _dcparser.DCPacker_get_current_field_name(self)

    def push(self):
        return _dcparser.DCPacker_push(self)

    def pop(self):
        return _dcparser.DCPacker_pop(self)

    def pack_double(self, value):
        return _dcparser.DCPacker_pack_double(self, value)

    def pack_int(self, value):
        return _dcparser.DCPacker_pack_int(self, value)

    def pack_uint(self, value):
        return _dcparser.DCPacker_pack_uint(self, value)

    def pack_int64(self, value):
        return _dcparser.DCPacker_pack_int64(self, value)

    def pack_uint64(self, value):
        return _dcparser.DCPacker_pack_uint64(self, value)

    def pack_string(self, value):
        return _dcparser.DCPacker_pack_string(self, value)

    def pack_blob(self, value):
        return _dcparser.DCPacker_pack_blob(self, value)

    def pack_literal_value(self, value):
        return _dcparser.DCPacker_pack_literal_value(self, value)

    def pack_default_value(self):
        return _dcparser.DCPacker_pack_default_value(self)

    def unpack_validate(self):
        return _dcparser.DCPacker_unpack_validate(self)

    def unpack_skip(self):
        return _dcparser.DCPacker_unpack_skip(self)

    def unpack_double(self, *args):
        return _dcparser.DCPacker_unpack_double(self, *args)

    def unpack_int(self, *args):
        return _dcparser.DCPacker_unpack_int(self, *args)

    def unpack_uint(self, *args):
        return _dcparser.DCPacker_unpack_uint(self, *args)

    def unpack_int64(self, *args):
        return _dcparser.DCPacker_unpack_int64(self, *args)

    def unpack_uint64(self, *args):
        return _dcparser.DCPacker_unpack_uint64(self, *args)

    def unpack_string(self, *args):
        return _dcparser.DCPacker_unpack_string(self, *args)

    def unpack_blob(self, *args):
        return _dcparser.DCPacker_unpack_blob(self, *args)

    def unpack_literal_value(self, *args):
        return _dcparser.DCPacker_unpack_literal_value(self, *args)

    def parse_and_pack(self, *args):
        return _dcparser.DCPacker_parse_and_pack(self, *args)

    def unpack_and_format(self, *args):
        return _dcparser.DCPacker_unpack_and_format(self, *args)

    def had_parse_error(self):
        return _dcparser.DCPacker_had_parse_error(self)

    def had_pack_error(self):
        return _dcparser.DCPacker_had_pack_error(self)

    def had_range_error(self):
        return _dcparser.DCPacker_had_range_error(self)

    def had_error(self):
        return _dcparser.DCPacker_had_error(self)

    def get_num_unpacked_bytes(self):
        return _dcparser.DCPacker_get_num_unpacked_bytes(self)

    def get_length(self):
        return _dcparser.DCPacker_get_length(self)

    def get_bytes(self):
        return _dcparser.DCPacker_get_bytes(self)

    def get_unpack_length(self):
        return _dcparser.DCPacker_get_unpack_length(self)

    def get_unpack_string(self):
        return _dcparser.DCPacker_get_unpack_string(self)

    def get_string(self, *args):
        return _dcparser.DCPacker_get_string(self, *args)

    def get_data(self):
        return _dcparser.DCPacker_get_data(self)

    def take_data(self):
        return _dcparser.DCPacker_take_data(self)

    def append_data(self, buffer, size):
        return _dcparser.DCPacker_append_data(self, buffer, size)

    def get_write_pointer(self, size):
        return _dcparser.DCPacker_get_write_pointer(self, size)

    def get_unpack_data(self):
        return _dcparser.DCPacker_get_unpack_data(self)

    @staticmethod
    def get_num_stack_elements_ever_allocated():
        return _dcparser.DCPacker_get_num_stack_elements_ever_allocated()

    def raw_pack_int8(self, value):
        return _dcparser.DCPacker_raw_pack_int8(self, value)

    def raw_pack_int16(self, value):
        return _dcparser.DCPacker_raw_pack_int16(self, value)

    def raw_pack_int32(self, value):
        return _dcparser.DCPacker_raw_pack_int32(self, value)

    def raw_pack_int64(self, value):
        return _dcparser.DCPacker_raw_pack_int64(self, value)

    def raw_pack_uint8(self, value):
        return _dcparser.DCPacker_raw_pack_uint8(self, value)

    def raw_pack_uint16(self, value):
        return _dcparser.DCPacker_raw_pack_uint16(self, value)

    def raw_pack_uint32(self, value):
        return _dcparser.DCPacker_raw_pack_uint32(self, value)

    def raw_pack_uint64(self, value):
        return _dcparser.DCPacker_raw_pack_uint64(self, value)

    def raw_pack_float64(self, value):
        return _dcparser.DCPacker_raw_pack_float64(self, value)

    def raw_pack_string(self, value):
        return _dcparser.DCPacker_raw_pack_string(self, value)

    def raw_pack_blob(self, value):
        return _dcparser.DCPacker_raw_pack_blob(self, value)

    def raw_unpack_int8(self, *args):
        return _dcparser.DCPacker_raw_unpack_int8(self, *args)

    def raw_unpack_int16(self, *args):
        return _dcparser.DCPacker_raw_unpack_int16(self, *args)

    def raw_unpack_int32(self, *args):
        return _dcparser.DCPacker_raw_unpack_int32(self, *args)

    def raw_unpack_int64(self, *args):
        return _dcparser.DCPacker_raw_unpack_int64(self, *args)

    def raw_unpack_uint8(self, *args):
        return _dcparser.DCPacker_raw_unpack_uint8(self, *args)

    def raw_unpack_uint16(self, *args):
        return _dcparser.DCPacker_raw_unpack_uint16(self, *args)

    def raw_unpack_uint32(self, *args):
        return _dcparser.DCPacker_raw_unpack_uint32(self, *args)

    def raw_unpack_uint64(self, *args):
        return _dcparser.DCPacker_raw_unpack_uint64(self, *args)

    def raw_unpack_float64(self, *args):
        return _dcparser.DCPacker_raw_unpack_float64(self, *args)

    def raw_unpack_string(self, *args):
        return _dcparser.DCPacker_raw_unpack_string(self, *args)

    def raw_unpack_blob(self, *args):
        return _dcparser.DCPacker_raw_unpack_blob(self, *args)

    @staticmethod
    def enquote_string(out, quote_mark, str):
        return _dcparser.DCPacker_enquote_string(out, quote_mark, str)

    @staticmethod
    def output_hex_string(out, str):
        return _dcparser.DCPacker_output_hex_string(out, str)

# Register DCPacker in _dcparser:
_dcparser.DCPacker_swigregister(DCPacker)

def DCPacker_get_num_stack_elements_ever_allocated():
    return _dcparser.DCPacker_get_num_stack_elements_ever_allocated()

def DCPacker_enquote_string(out, quote_mark, str):
    return _dcparser.DCPacker_enquote_string(out, quote_mark, str)

def DCPacker_output_hex_string(out, str):
    return _dcparser.DCPacker_output_hex_string(out, str)

class DCPackerCatalog(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def get_num_entries(self):
        return _dcparser.DCPackerCatalog_get_num_entries(self)

    def get_entry(self, n):
        return _dcparser.DCPackerCatalog_get_entry(self, n)

    def find_entry_by_name(self, name):
        return _dcparser.DCPackerCatalog_find_entry_by_name(self, name)

    def find_entry_by_field(self, field):
        return _dcparser.DCPackerCatalog_find_entry_by_field(self, field)

    def get_live_catalog(self, data, length):
        return _dcparser.DCPackerCatalog_get_live_catalog(self, data, length)

    def release_live_catalog(self, live_catalog):
        return _dcparser.DCPackerCatalog_release_live_catalog(self, live_catalog)

# Register DCPackerCatalog in _dcparser:
_dcparser.DCPackerCatalog_swigregister(DCPackerCatalog)

PT_invalid = _dcparser.PT_invalid
PT_double = _dcparser.PT_double
PT_int = _dcparser.PT_int
PT_uint = _dcparser.PT_uint
PT_int64 = _dcparser.PT_int64
PT_uint64 = _dcparser.PT_uint64
PT_string = _dcparser.PT_string
PT_blob = _dcparser.PT_blob
PT_array = _dcparser.PT_array
PT_field = _dcparser.PT_field
PT_class = _dcparser.PT_class
PT_switch = _dcparser.PT_switch
class DCPackerInterface(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _dcparser.delete_DCPackerInterface

    def get_name(self):
        return _dcparser.DCPackerInterface_get_name(self)

    def find_seek_index(self, name):
        return _dcparser.DCPackerInterface_find_seek_index(self, name)

    def as_field(self, *args):
        return _dcparser.DCPackerInterface_as_field(self, *args)

    def as_switch_parameter(self, *args):
        return _dcparser.DCPackerInterface_as_switch_parameter(self, *args)

    def as_class_parameter(self, *args):
        return _dcparser.DCPackerInterface_as_class_parameter(self, *args)

    def check_match(self, *args):
        return _dcparser.DCPackerInterface_check_match(self, *args)

    def set_name(self, name):
        return _dcparser.DCPackerInterface_set_name(self, name)

    def has_fixed_byte_size(self):
        return _dcparser.DCPackerInterface_has_fixed_byte_size(self)

    def get_fixed_byte_size(self):
        return _dcparser.DCPackerInterface_get_fixed_byte_size(self)

    def has_fixed_structure(self):
        return _dcparser.DCPackerInterface_has_fixed_structure(self)

    def has_range_limits(self):
        return _dcparser.DCPackerInterface_has_range_limits(self)

    def get_num_length_bytes(self):
        return _dcparser.DCPackerInterface_get_num_length_bytes(self)

    def has_nested_fields(self):
        return _dcparser.DCPackerInterface_has_nested_fields(self)

    def get_num_nested_fields(self):
        return _dcparser.DCPackerInterface_get_num_nested_fields(self)

    def calc_num_nested_fields(self, length_bytes):
        return _dcparser.DCPackerInterface_calc_num_nested_fields(self, length_bytes)

    def get_nested_field(self, n):
        return _dcparser.DCPackerInterface_get_nested_field(self, n)

    def validate_num_nested_fields(self, num_nested_fields):
        return _dcparser.DCPackerInterface_validate_num_nested_fields(self, num_nested_fields)

    def get_pack_type(self):
        return _dcparser.DCPackerInterface_get_pack_type(self)

    def pack_double(self, pack_data, value, pack_error, range_error):
        return _dcparser.DCPackerInterface_pack_double(self, pack_data, value, pack_error, range_error)

    def pack_int(self, pack_data, value, pack_error, range_error):
        return _dcparser.DCPackerInterface_pack_int(self, pack_data, value, pack_error, range_error)

    def pack_uint(self, pack_data, value, pack_error, range_error):
        return _dcparser.DCPackerInterface_pack_uint(self, pack_data, value, pack_error, range_error)

    def pack_int64(self, pack_data, value, pack_error, range_error):
        return _dcparser.DCPackerInterface_pack_int64(self, pack_data, value, pack_error, range_error)

    def pack_uint64(self, pack_data, value, pack_error, range_error):
        return _dcparser.DCPackerInterface_pack_uint64(self, pack_data, value, pack_error, range_error)

    def pack_string(self, pack_data, value, pack_error, range_error):
        return _dcparser.DCPackerInterface_pack_string(self, pack_data, value, pack_error, range_error)

    def pack_blob(self, pack_data, value, pack_error, range_error):
        return _dcparser.DCPackerInterface_pack_blob(self, pack_data, value, pack_error, range_error)

    def pack_default_value(self, pack_data, pack_error):
        return _dcparser.DCPackerInterface_pack_default_value(self, pack_data, pack_error)

    def unpack_double(self, data, length, p, value, pack_error, range_error):
        return _dcparser.DCPackerInterface_unpack_double(self, data, length, p, value, pack_error, range_error)

    def unpack_int(self, data, length, p, value, pack_error, range_error):
        return _dcparser.DCPackerInterface_unpack_int(self, data, length, p, value, pack_error, range_error)

    def unpack_uint(self, data, length, p, value, pack_error, range_error):
        return _dcparser.DCPackerInterface_unpack_uint(self, data, length, p, value, pack_error, range_error)

    def unpack_int64(self, data, length, p, value, pack_error, range_error):
        return _dcparser.DCPackerInterface_unpack_int64(self, data, length, p, value, pack_error, range_error)

    def unpack_uint64(self, data, length, p, value, pack_error, range_error):
        return _dcparser.DCPackerInterface_unpack_uint64(self, data, length, p, value, pack_error, range_error)

    def unpack_string(self, data, length, p, value, pack_error, range_error):
        return _dcparser.DCPackerInterface_unpack_string(self, data, length, p, value, pack_error, range_error)

    def unpack_blob(self, data, length, p, value, pack_error, range_error):
        return _dcparser.DCPackerInterface_unpack_blob(self, data, length, p, value, pack_error, range_error)

    def unpack_validate(self, data, length, p, pack_error, range_error):
        return _dcparser.DCPackerInterface_unpack_validate(self, data, length, p, pack_error, range_error)

    def unpack_skip(self, data, length, p, pack_error):
        return _dcparser.DCPackerInterface_unpack_skip(self, data, length, p, pack_error)

    @staticmethod
    def do_pack_int8(buffer, value):
        return _dcparser.DCPackerInterface_do_pack_int8(buffer, value)

    @staticmethod
    def do_pack_int16(buffer, value):
        return _dcparser.DCPackerInterface_do_pack_int16(buffer, value)

    @staticmethod
    def do_pack_int32(buffer, value):
        return _dcparser.DCPackerInterface_do_pack_int32(buffer, value)

    @staticmethod
    def do_pack_int64(buffer, value):
        return _dcparser.DCPackerInterface_do_pack_int64(buffer, value)

    @staticmethod
    def do_pack_uint8(buffer, value):
        return _dcparser.DCPackerInterface_do_pack_uint8(buffer, value)

    @staticmethod
    def do_pack_uint16(buffer, value):
        return _dcparser.DCPackerInterface_do_pack_uint16(buffer, value)

    @staticmethod
    def do_pack_uint32(buffer, value):
        return _dcparser.DCPackerInterface_do_pack_uint32(buffer, value)

    @staticmethod
    def do_pack_uint64(buffer, value):
        return _dcparser.DCPackerInterface_do_pack_uint64(buffer, value)

    @staticmethod
    def do_pack_float64(buffer, value):
        return _dcparser.DCPackerInterface_do_pack_float64(buffer, value)

    @staticmethod
    def do_unpack_int8(buffer):
        return _dcparser.DCPackerInterface_do_unpack_int8(buffer)

    @staticmethod
    def do_unpack_int16(buffer):
        return _dcparser.DCPackerInterface_do_unpack_int16(buffer)

    @staticmethod
    def do_unpack_int32(buffer):
        return _dcparser.DCPackerInterface_do_unpack_int32(buffer)

    @staticmethod
    def do_unpack_int64(buffer):
        return _dcparser.DCPackerInterface_do_unpack_int64(buffer)

    @staticmethod
    def do_unpack_uint8(buffer):
        return _dcparser.DCPackerInterface_do_unpack_uint8(buffer)

    @staticmethod
    def do_unpack_uint16(buffer):
        return _dcparser.DCPackerInterface_do_unpack_uint16(buffer)

    @staticmethod
    def do_unpack_uint32(buffer):
        return _dcparser.DCPackerInterface_do_unpack_uint32(buffer)

    @staticmethod
    def do_unpack_uint64(buffer):
        return _dcparser.DCPackerInterface_do_unpack_uint64(buffer)

    @staticmethod
    def do_unpack_float64(buffer):
        return _dcparser.DCPackerInterface_do_unpack_float64(buffer)

    @staticmethod
    def validate_int_limits(value, num_bits, range_error):
        return _dcparser.DCPackerInterface_validate_int_limits(value, num_bits, range_error)

    @staticmethod
    def validate_int64_limits(value, num_bits, range_error):
        return _dcparser.DCPackerInterface_validate_int64_limits(value, num_bits, range_error)

    @staticmethod
    def validate_uint_limits(value, num_bits, range_error):
        return _dcparser.DCPackerInterface_validate_uint_limits(value, num_bits, range_error)

    @staticmethod
    def validate_uint64_limits(value, num_bits, range_error):
        return _dcparser.DCPackerInterface_validate_uint64_limits(value, num_bits, range_error)

    def get_catalog(self):
        return _dcparser.DCPackerInterface_get_catalog(self)

    def do_check_match_simple_parameter(self, other):
        return _dcparser.DCPackerInterface_do_check_match_simple_parameter(self, other)

    def do_check_match_class_parameter(self, other):
        return _dcparser.DCPackerInterface_do_check_match_class_parameter(self, other)

    def do_check_match_switch_parameter(self, other):
        return _dcparser.DCPackerInterface_do_check_match_switch_parameter(self, other)

    def do_check_match_array_parameter(self, other):
        return _dcparser.DCPackerInterface_do_check_match_array_parameter(self, other)

    def do_check_match_atomic_field(self, other):
        return _dcparser.DCPackerInterface_do_check_match_atomic_field(self, other)

    def do_check_match_molecular_field(self, other):
        return _dcparser.DCPackerInterface_do_check_match_molecular_field(self, other)

# Register DCPackerInterface in _dcparser:
_dcparser.DCPackerInterface_swigregister(DCPackerInterface)

def DCPackerInterface_do_pack_int8(buffer, value):
    return _dcparser.DCPackerInterface_do_pack_int8(buffer, value)

def DCPackerInterface_do_pack_int16(buffer, value):
    return _dcparser.DCPackerInterface_do_pack_int16(buffer, value)

def DCPackerInterface_do_pack_int32(buffer, value):
    return _dcparser.DCPackerInterface_do_pack_int32(buffer, value)

def DCPackerInterface_do_pack_int64(buffer, value):
    return _dcparser.DCPackerInterface_do_pack_int64(buffer, value)

def DCPackerInterface_do_pack_uint8(buffer, value):
    return _dcparser.DCPackerInterface_do_pack_uint8(buffer, value)

def DCPackerInterface_do_pack_uint16(buffer, value):
    return _dcparser.DCPackerInterface_do_pack_uint16(buffer, value)

def DCPackerInterface_do_pack_uint32(buffer, value):
    return _dcparser.DCPackerInterface_do_pack_uint32(buffer, value)

def DCPackerInterface_do_pack_uint64(buffer, value):
    return _dcparser.DCPackerInterface_do_pack_uint64(buffer, value)

def DCPackerInterface_do_pack_float64(buffer, value):
    return _dcparser.DCPackerInterface_do_pack_float64(buffer, value)

def DCPackerInterface_do_unpack_int8(buffer):
    return _dcparser.DCPackerInterface_do_unpack_int8(buffer)

def DCPackerInterface_do_unpack_int16(buffer):
    return _dcparser.DCPackerInterface_do_unpack_int16(buffer)

def DCPackerInterface_do_unpack_int32(buffer):
    return _dcparser.DCPackerInterface_do_unpack_int32(buffer)

def DCPackerInterface_do_unpack_int64(buffer):
    return _dcparser.DCPackerInterface_do_unpack_int64(buffer)

def DCPackerInterface_do_unpack_uint8(buffer):
    return _dcparser.DCPackerInterface_do_unpack_uint8(buffer)

def DCPackerInterface_do_unpack_uint16(buffer):
    return _dcparser.DCPackerInterface_do_unpack_uint16(buffer)

def DCPackerInterface_do_unpack_uint32(buffer):
    return _dcparser.DCPackerInterface_do_unpack_uint32(buffer)

def DCPackerInterface_do_unpack_uint64(buffer):
    return _dcparser.DCPackerInterface_do_unpack_uint64(buffer)

def DCPackerInterface_do_unpack_float64(buffer):
    return _dcparser.DCPackerInterface_do_unpack_float64(buffer)

def DCPackerInterface_validate_int_limits(value, num_bits, range_error):
    return _dcparser.DCPackerInterface_validate_int_limits(value, num_bits, range_error)

def DCPackerInterface_validate_int64_limits(value, num_bits, range_error):
    return _dcparser.DCPackerInterface_validate_int64_limits(value, num_bits, range_error)

def DCPackerInterface_validate_uint_limits(value, num_bits, range_error):
    return _dcparser.DCPackerInterface_validate_uint_limits(value, num_bits, range_error)

def DCPackerInterface_validate_uint64_limits(value, num_bits, range_error):
    return _dcparser.DCPackerInterface_validate_uint64_limits(value, num_bits, range_error)


def indent(out, indent_level):
    return _dcparser.indent(out, indent_level)
class DCField(DCPackerInterface, DCKeywordList):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _dcparser.delete_DCField

    def get_number(self):
        return _dcparser.DCField_get_number(self)

    def get_class(self):
        return _dcparser.DCField_get_class(self)

    def as_field(self, *args):
        return _dcparser.DCField_as_field(self, *args)

    def as_atomic_field(self, *args):
        return _dcparser.DCField_as_atomic_field(self, *args)

    def as_molecular_field(self, *args):
        return _dcparser.DCField_as_molecular_field(self, *args)

    def as_parameter(self, *args):
        return _dcparser.DCField_as_parameter(self, *args)

    def format_data(self, packed_data, show_field_names=True):
        return _dcparser.DCField_format_data(self, packed_data, show_field_names)

    def parse_string(self, formatted_string):
        return _dcparser.DCField_parse_string(self, formatted_string)

    def validate_ranges(self, packed_data):
        return _dcparser.DCField_validate_ranges(self, packed_data)

    def has_default_value(self):
        return _dcparser.DCField_has_default_value(self)

    def get_default_value(self):
        return _dcparser.DCField_get_default_value(self)

    def is_bogus_field(self):
        return _dcparser.DCField_is_bogus_field(self)

    def is_required(self):
        return _dcparser.DCField_is_required(self)

    def is_broadcast(self):
        return _dcparser.DCField_is_broadcast(self)

    def is_ram(self):
        return _dcparser.DCField_is_ram(self)

    def is_db(self):
        return _dcparser.DCField_is_db(self)

    def is_clsend(self):
        return _dcparser.DCField_is_clsend(self)

    def is_clrecv(self):
        return _dcparser.DCField_is_clrecv(self)

    def is_ownsend(self):
        return _dcparser.DCField_is_ownsend(self)

    def is_ownrecv(self):
        return _dcparser.DCField_is_ownrecv(self)

    def is_airecv(self):
        return _dcparser.DCField_is_airecv(self)

    def output(self, *args):
        return _dcparser.DCField_output(self, *args)

    def write(self, *args):
        return _dcparser.DCField_write(self, *args)

    def generate_hash(self, hashgen):
        return _dcparser.DCField_generate_hash(self, hashgen)

    def pack_default_value(self, pack_data, pack_error):
        return _dcparser.DCField_pack_default_value(self, pack_data, pack_error)

    def set_name(self, name):
        return _dcparser.DCField_set_name(self, name)

    def set_number(self, number):
        return _dcparser.DCField_set_number(self, number)

    def set_class(self, dclass):
        return _dcparser.DCField_set_class(self, dclass)

    def set_default_value(self, default_value):
        return _dcparser.DCField_set_default_value(self, default_value)

# Register DCField in _dcparser:
_dcparser.DCField_swigregister(DCField)

class DCFile(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _dcparser.DCFile_swiginit(self, _dcparser.new_DCFile())
    __swig_destroy__ = _dcparser.delete_DCFile

    def clear(self):
        return _dcparser.DCFile_clear(self)

    def read(self, *args):
        return _dcparser.DCFile_read(self, *args)

    def write(self, *args):
        return _dcparser.DCFile_write(self, *args)

    def get_num_classes(self):
        return _dcparser.DCFile_get_num_classes(self)

    def get_class(self, n):
        return _dcparser.DCFile_get_class(self, n)

    def get_class_by_name(self, name):
        return _dcparser.DCFile_get_class_by_name(self, name)

    def get_switch_by_name(self, name):
        return _dcparser.DCFile_get_switch_by_name(self, name)

    def get_field_by_index(self, index_number):
        return _dcparser.DCFile_get_field_by_index(self, index_number)

    def all_objects_valid(self):
        return _dcparser.DCFile_all_objects_valid(self)

    def get_num_import_modules(self):
        return _dcparser.DCFile_get_num_import_modules(self)

    def get_import_module(self, n):
        return _dcparser.DCFile_get_import_module(self, n)

    def get_num_import_symbols(self, n):
        return _dcparser.DCFile_get_num_import_symbols(self, n)

    def get_import_symbol(self, n, i):
        return _dcparser.DCFile_get_import_symbol(self, n, i)

    def get_num_typedefs(self):
        return _dcparser.DCFile_get_num_typedefs(self)

    def get_typedef(self, n):
        return _dcparser.DCFile_get_typedef(self, n)

    def get_typedef_by_name(self, name):
        return _dcparser.DCFile_get_typedef_by_name(self, name)

    def get_num_keywords(self):
        return _dcparser.DCFile_get_num_keywords(self)

    def get_keyword(self, n):
        return _dcparser.DCFile_get_keyword(self, n)

    def get_keyword_by_name(self, name):
        return _dcparser.DCFile_get_keyword_by_name(self, name)

    def get_hash(self):
        return _dcparser.DCFile_get_hash(self)

    def generate_hash(self, hashgen):
        return _dcparser.DCFile_generate_hash(self, hashgen)

    def add_class(self, dclass):
        return _dcparser.DCFile_add_class(self, dclass)

    def add_switch(self, dswitch):
        return _dcparser.DCFile_add_switch(self, dswitch)

    def add_import_module(self, import_module):
        return _dcparser.DCFile_add_import_module(self, import_module)

    def add_import_symbol(self, import_symbol):
        return _dcparser.DCFile_add_import_symbol(self, import_symbol)

    def add_typedef(self, dtypedef):
        return _dcparser.DCFile_add_typedef(self, dtypedef)

    def add_keyword(self, name):
        return _dcparser.DCFile_add_keyword(self, name)

    def add_thing_to_delete(self, decl):
        return _dcparser.DCFile_add_thing_to_delete(self, decl)

    def set_new_index_number(self, field):
        return _dcparser.DCFile_set_new_index_number(self, field)

    def check_inherited_fields(self):
        return _dcparser.DCFile_check_inherited_fields(self)

    def mark_inherited_fields_stale(self):
        return _dcparser.DCFile_mark_inherited_fields_stale(self)

# Register DCFile in _dcparser:
_dcparser.DCFile_swigregister(DCFile)

class DCParameter(DCField):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _dcparser.delete_DCParameter

    def as_parameter(self, *args):
        return _dcparser.DCParameter_as_parameter(self, *args)

    def as_simple_parameter(self, *args):
        return _dcparser.DCParameter_as_simple_parameter(self, *args)

    def as_class_parameter(self, *args):
        return _dcparser.DCParameter_as_class_parameter(self, *args)

    def as_switch_parameter(self, *args):
        return _dcparser.DCParameter_as_switch_parameter(self, *args)

    def as_array_parameter(self, *args):
        return _dcparser.DCParameter_as_array_parameter(self, *args)

    def make_copy(self):
        return _dcparser.DCParameter_make_copy(self)

    def is_valid(self):
        return _dcparser.DCParameter_is_valid(self)

    def get_typedef(self):
        return _dcparser.DCParameter_get_typedef(self)

    def set_typedef(self, dtypedef):
        return _dcparser.DCParameter_set_typedef(self, dtypedef)

    def append_array_specification(self, size):
        return _dcparser.DCParameter_append_array_specification(self, size)

    def output(self, out, brief):
        return _dcparser.DCParameter_output(self, out, brief)

    def write(self, out, brief, indent_level):
        return _dcparser.DCParameter_write(self, out, brief, indent_level)

    def output_instance(self, out, brief, prename, name, postname):
        return _dcparser.DCParameter_output_instance(self, out, brief, prename, name, postname)

    def write_instance(self, out, brief, indent_level, prename, name, postname):
        return _dcparser.DCParameter_write_instance(self, out, brief, indent_level, prename, name, postname)

    def output_typedef_name(self, out, brief, prename, name, postname):
        return _dcparser.DCParameter_output_typedef_name(self, out, brief, prename, name, postname)

    def write_typedef_name(self, out, brief, indent_level, prename, name, postname):
        return _dcparser.DCParameter_write_typedef_name(self, out, brief, indent_level, prename, name, postname)

    def generate_hash(self, hashgen):
        return _dcparser.DCParameter_generate_hash(self, hashgen)

# Register DCParameter in _dcparser:
_dcparser.DCParameter_swigregister(DCParameter)

class DCClassParameter(DCParameter):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _dcparser.DCClassParameter_swiginit(self, _dcparser.new_DCClassParameter(*args))

    def as_class_parameter(self, *args):
        return _dcparser.DCClassParameter_as_class_parameter(self, *args)

    def make_copy(self):
        return _dcparser.DCClassParameter_make_copy(self)

    def is_valid(self):
        return _dcparser.DCClassParameter_is_valid(self)

    def get_class(self):
        return _dcparser.DCClassParameter_get_class(self)

    def get_nested_field(self, n):
        return _dcparser.DCClassParameter_get_nested_field(self, n)

    def output_instance(self, out, brief, prename, name, postname):
        return _dcparser.DCClassParameter_output_instance(self, out, brief, prename, name, postname)

    def generate_hash(self, hashgen):
        return _dcparser.DCClassParameter_generate_hash(self, hashgen)
    __swig_destroy__ = _dcparser.delete_DCClassParameter

# Register DCClassParameter in _dcparser:
_dcparser.DCClassParameter_swigregister(DCClassParameter)

class DCArrayParameter(DCParameter):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _dcparser.DCArrayParameter_swiginit(self, _dcparser.new_DCArrayParameter(*args))
    __swig_destroy__ = _dcparser.delete_DCArrayParameter

    def as_array_parameter(self, *args):
        return _dcparser.DCArrayParameter_as_array_parameter(self, *args)

    def make_copy(self):
        return _dcparser.DCArrayParameter_make_copy(self)

    def is_valid(self):
        return _dcparser.DCArrayParameter_is_valid(self)

    def get_element_type(self):
        return _dcparser.DCArrayParameter_get_element_type(self)

    def get_array_size(self):
        return _dcparser.DCArrayParameter_get_array_size(self)

    def append_array_specification(self, size):
        return _dcparser.DCArrayParameter_append_array_specification(self, size)

    def calc_num_nested_fields(self, length_bytes):
        return _dcparser.DCArrayParameter_calc_num_nested_fields(self, length_bytes)

    def get_nested_field(self, n):
        return _dcparser.DCArrayParameter_get_nested_field(self, n)

    def validate_num_nested_fields(self, num_nested_fields):
        return _dcparser.DCArrayParameter_validate_num_nested_fields(self, num_nested_fields)

    def output_instance(self, out, brief, prename, name, postname):
        return _dcparser.DCArrayParameter_output_instance(self, out, brief, prename, name, postname)

    def generate_hash(self, hashgen):
        return _dcparser.DCArrayParameter_generate_hash(self, hashgen)

    def pack_string(self, pack_data, value, pack_error, range_error):
        return _dcparser.DCArrayParameter_pack_string(self, pack_data, value, pack_error, range_error)

    def pack_blob(self, pack_data, value, pack_error, range_error):
        return _dcparser.DCArrayParameter_pack_blob(self, pack_data, value, pack_error, range_error)

    def pack_default_value(self, pack_data, pack_error):
        return _dcparser.DCArrayParameter_pack_default_value(self, pack_data, pack_error)

    def unpack_string(self, data, length, p, value, pack_error, range_error):
        return _dcparser.DCArrayParameter_unpack_string(self, data, length, p, value, pack_error, range_error)

    def unpack_blob(self, data, length, p, value, pack_error, range_error):
        return _dcparser.DCArrayParameter_unpack_blob(self, data, length, p, value, pack_error, range_error)

# Register DCArrayParameter in _dcparser:
_dcparser.DCArrayParameter_swigregister(DCArrayParameter)

class DCSimpleParameter(DCParameter):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _dcparser.DCSimpleParameter_swiginit(self, _dcparser.new_DCSimpleParameter(*args))

    def as_simple_parameter(self, *args):
        return _dcparser.DCSimpleParameter_as_simple_parameter(self, *args)

    def make_copy(self):
        return _dcparser.DCSimpleParameter_make_copy(self)

    def is_valid(self):
        return _dcparser.DCSimpleParameter_is_valid(self)

    def get_type(self):
        return _dcparser.DCSimpleParameter_get_type(self)

    def has_modulus(self):
        return _dcparser.DCSimpleParameter_has_modulus(self)

    def get_modulus(self):
        return _dcparser.DCSimpleParameter_get_modulus(self)

    def get_divisor(self):
        return _dcparser.DCSimpleParameter_get_divisor(self)

    def is_numeric_type(self):
        return _dcparser.DCSimpleParameter_is_numeric_type(self)

    def set_modulus(self, modulus):
        return _dcparser.DCSimpleParameter_set_modulus(self, modulus)

    def set_divisor(self, divisor):
        return _dcparser.DCSimpleParameter_set_divisor(self, divisor)

    def set_range(self, range):
        return _dcparser.DCSimpleParameter_set_range(self, range)

    def calc_num_nested_fields(self, length_bytes):
        return _dcparser.DCSimpleParameter_calc_num_nested_fields(self, length_bytes)

    def get_nested_field(self, n):
        return _dcparser.DCSimpleParameter_get_nested_field(self, n)

    def pack_double(self, pack_data, value, pack_error, range_error):
        return _dcparser.DCSimpleParameter_pack_double(self, pack_data, value, pack_error, range_error)

    def pack_int(self, pack_data, value, pack_error, range_error):
        return _dcparser.DCSimpleParameter_pack_int(self, pack_data, value, pack_error, range_error)

    def pack_uint(self, pack_data, value, pack_error, range_error):
        return _dcparser.DCSimpleParameter_pack_uint(self, pack_data, value, pack_error, range_error)

    def pack_int64(self, pack_data, value, pack_error, range_error):
        return _dcparser.DCSimpleParameter_pack_int64(self, pack_data, value, pack_error, range_error)

    def pack_uint64(self, pack_data, value, pack_error, range_error):
        return _dcparser.DCSimpleParameter_pack_uint64(self, pack_data, value, pack_error, range_error)

    def pack_string(self, pack_data, value, pack_error, range_error):
        return _dcparser.DCSimpleParameter_pack_string(self, pack_data, value, pack_error, range_error)

    def pack_blob(self, pack_data, value, pack_error, range_error):
        return _dcparser.DCSimpleParameter_pack_blob(self, pack_data, value, pack_error, range_error)

    def pack_default_value(self, pack_data, pack_error):
        return _dcparser.DCSimpleParameter_pack_default_value(self, pack_data, pack_error)

    def unpack_double(self, data, length, p, value, pack_error, range_error):
        return _dcparser.DCSimpleParameter_unpack_double(self, data, length, p, value, pack_error, range_error)

    def unpack_int(self, data, length, p, value, pack_error, range_error):
        return _dcparser.DCSimpleParameter_unpack_int(self, data, length, p, value, pack_error, range_error)

    def unpack_uint(self, data, length, p, value, pack_error, range_error):
        return _dcparser.DCSimpleParameter_unpack_uint(self, data, length, p, value, pack_error, range_error)

    def unpack_int64(self, data, length, p, value, pack_error, range_error):
        return _dcparser.DCSimpleParameter_unpack_int64(self, data, length, p, value, pack_error, range_error)

    def unpack_uint64(self, data, length, p, value, pack_error, range_error):
        return _dcparser.DCSimpleParameter_unpack_uint64(self, data, length, p, value, pack_error, range_error)

    def unpack_string(self, data, length, p, value, pack_error, range_error):
        return _dcparser.DCSimpleParameter_unpack_string(self, data, length, p, value, pack_error, range_error)

    def unpack_blob(self, data, length, p, value, pack_error, range_error):
        return _dcparser.DCSimpleParameter_unpack_blob(self, data, length, p, value, pack_error, range_error)

    def unpack_validate(self, data, length, p, pack_error, range_error):
        return _dcparser.DCSimpleParameter_unpack_validate(self, data, length, p, pack_error, range_error)

    def unpack_skip(self, data, length, p, pack_error):
        return _dcparser.DCSimpleParameter_unpack_skip(self, data, length, p, pack_error)

    def output_instance(self, out, brief, prename, name, postname):
        return _dcparser.DCSimpleParameter_output_instance(self, out, brief, prename, name, postname)

    def generate_hash(self, hashgen):
        return _dcparser.DCSimpleParameter_generate_hash(self, hashgen)
    __swig_destroy__ = _dcparser.delete_DCSimpleParameter

# Register DCSimpleParameter in _dcparser:
_dcparser.DCSimpleParameter_swigregister(DCSimpleParameter)

class DCSwitchParameter(DCParameter):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _dcparser.DCSwitchParameter_swiginit(self, _dcparser.new_DCSwitchParameter(*args))

    def as_switch_parameter(self, *args):
        return _dcparser.DCSwitchParameter_as_switch_parameter(self, *args)

    def make_copy(self):
        return _dcparser.DCSwitchParameter_make_copy(self)

    def is_valid(self):
        return _dcparser.DCSwitchParameter_is_valid(self)

    def get_switch(self):
        return _dcparser.DCSwitchParameter_get_switch(self)

    def get_nested_field(self, n):
        return _dcparser.DCSwitchParameter_get_nested_field(self, n)

    def apply_switch(self, value_data, length):
        return _dcparser.DCSwitchParameter_apply_switch(self, value_data, length)

    def output_instance(self, out, brief, prename, name, postname):
        return _dcparser.DCSwitchParameter_output_instance(self, out, brief, prename, name, postname)

    def write_instance(self, out, brief, indent_level, prename, name, postname):
        return _dcparser.DCSwitchParameter_write_instance(self, out, brief, indent_level, prename, name, postname)

    def generate_hash(self, hashgen):
        return _dcparser.DCSwitchParameter_generate_hash(self, hashgen)

    def pack_default_value(self, pack_data, pack_error):
        return _dcparser.DCSwitchParameter_pack_default_value(self, pack_data, pack_error)
    __swig_destroy__ = _dcparser.delete_DCSwitchParameter

# Register DCSwitchParameter in _dcparser:
_dcparser.DCSwitchParameter_swigregister(DCSwitchParameter)

class DCAtomicField(DCField):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, name, dclass, bogus_field):
        _dcparser.DCAtomicField_swiginit(self, _dcparser.new_DCAtomicField(name, dclass, bogus_field))
    __swig_destroy__ = _dcparser.delete_DCAtomicField

    def as_atomic_field(self, *args):
        return _dcparser.DCAtomicField_as_atomic_field(self, *args)

    def get_num_elements(self):
        return _dcparser.DCAtomicField_get_num_elements(self)

    def get_element(self, n):
        return _dcparser.DCAtomicField_get_element(self, n)

    def get_element_default(self, n):
        return _dcparser.DCAtomicField_get_element_default(self, n)

    def has_element_default(self, n):
        return _dcparser.DCAtomicField_has_element_default(self, n)

    def get_element_name(self, n):
        return _dcparser.DCAtomicField_get_element_name(self, n)

    def get_element_type(self, n):
        return _dcparser.DCAtomicField_get_element_type(self, n)

    def get_element_divisor(self, n):
        return _dcparser.DCAtomicField_get_element_divisor(self, n)

    def add_element(self, element):
        return _dcparser.DCAtomicField_add_element(self, element)

    def output(self, out, brief):
        return _dcparser.DCAtomicField_output(self, out, brief)

    def write(self, out, brief, indent_level):
        return _dcparser.DCAtomicField_write(self, out, brief, indent_level)

    def generate_hash(self, hashgen):
        return _dcparser.DCAtomicField_generate_hash(self, hashgen)

    def get_nested_field(self, n):
        return _dcparser.DCAtomicField_get_nested_field(self, n)

# Register DCAtomicField in _dcparser:
_dcparser.DCAtomicField_swigregister(DCAtomicField)

class DCMolecularField(DCField):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, name, dclass):
        _dcparser.DCMolecularField_swiginit(self, _dcparser.new_DCMolecularField(name, dclass))

    def as_molecular_field(self, *args):
        return _dcparser.DCMolecularField_as_molecular_field(self, *args)

    def get_num_atomics(self):
        return _dcparser.DCMolecularField_get_num_atomics(self)

    def get_atomic(self, n):
        return _dcparser.DCMolecularField_get_atomic(self, n)

    def add_atomic(self, atomic):
        return _dcparser.DCMolecularField_add_atomic(self, atomic)

    def output(self, out, brief):
        return _dcparser.DCMolecularField_output(self, out, brief)

    def write(self, out, brief, indent_level):
        return _dcparser.DCMolecularField_write(self, out, brief, indent_level)

    def generate_hash(self, hashgen):
        return _dcparser.DCMolecularField_generate_hash(self, hashgen)

    def get_nested_field(self, n):
        return _dcparser.DCMolecularField_get_nested_field(self, n)
    __swig_destroy__ = _dcparser.delete_DCMolecularField

# Register DCMolecularField in _dcparser:
_dcparser.DCMolecularField_swigregister(DCMolecularField)

ST_int8 = _dcparser.ST_int8
ST_int16 = _dcparser.ST_int16
ST_int32 = _dcparser.ST_int32
ST_int64 = _dcparser.ST_int64
ST_uint8 = _dcparser.ST_uint8
ST_uint16 = _dcparser.ST_uint16
ST_uint32 = _dcparser.ST_uint32
ST_uint64 = _dcparser.ST_uint64
ST_float64 = _dcparser.ST_float64
ST_string = _dcparser.ST_string
ST_blob = _dcparser.ST_blob
ST_blob32 = _dcparser.ST_blob32
ST_int16array = _dcparser.ST_int16array
ST_int32array = _dcparser.ST_int32array
ST_uint16array = _dcparser.ST_uint16array
ST_uint32array = _dcparser.ST_uint32array
ST_int8array = _dcparser.ST_int8array
ST_uint8array = _dcparser.ST_uint8array
ST_uint32uint8array = _dcparser.ST_uint32uint8array
ST_char = _dcparser.ST_char
ST_invalid = _dcparser.ST_invalid
class DCSwitch(DCDeclaration):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, name, key_parameter):
        _dcparser.DCSwitch_swiginit(self, _dcparser.new_DCSwitch(name, key_parameter))
    __swig_destroy__ = _dcparser.delete_DCSwitch

    def as_switch(self, *args):
        return _dcparser.DCSwitch_as_switch(self, *args)

    def get_name(self):
        return _dcparser.DCSwitch_get_name(self)

    def get_key_parameter(self):
        return _dcparser.DCSwitch_get_key_parameter(self)

    def get_num_cases(self):
        return _dcparser.DCSwitch_get_num_cases(self)

    def get_case_by_value(self, case_value):
        return _dcparser.DCSwitch_get_case_by_value(self, case_value)

    def get_case(self, n):
        return _dcparser.DCSwitch_get_case(self, n)

    def get_default_case(self):
        return _dcparser.DCSwitch_get_default_case(self)

    def get_value(self, case_index):
        return _dcparser.DCSwitch_get_value(self, case_index)

    def get_num_fields(self, case_index):
        return _dcparser.DCSwitch_get_num_fields(self, case_index)

    def get_field(self, case_index, n):
        return _dcparser.DCSwitch_get_field(self, case_index, n)

    def get_field_by_name(self, case_index, name):
        return _dcparser.DCSwitch_get_field_by_name(self, case_index, name)

    def is_field_valid(self):
        return _dcparser.DCSwitch_is_field_valid(self)

    def add_case(self, value):
        return _dcparser.DCSwitch_add_case(self, value)

    def add_invalid_case(self):
        return _dcparser.DCSwitch_add_invalid_case(self)

    def add_default(self):
        return _dcparser.DCSwitch_add_default(self)

    def add_field(self, field):
        return _dcparser.DCSwitch_add_field(self, field)

    def add_break(self):
        return _dcparser.DCSwitch_add_break(self)

    def apply_switch(self, value_data, length):
        return _dcparser.DCSwitch_apply_switch(self, value_data, length)

    def output(self, out, brief):
        return _dcparser.DCSwitch_output(self, out, brief)

    def write(self, out, brief, indent_level):
        return _dcparser.DCSwitch_write(self, out, brief, indent_level)

    def output_instance(self, out, brief, prename, name, postname):
        return _dcparser.DCSwitch_output_instance(self, out, brief, prename, name, postname)

    def write_instance(self, out, brief, indent_level, prename, name, postname):
        return _dcparser.DCSwitch_write_instance(self, out, brief, indent_level, prename, name, postname)

    def generate_hash(self, hashgen):
        return _dcparser.DCSwitch_generate_hash(self, hashgen)

    def pack_default_value(self, pack_data, pack_error):
        return _dcparser.DCSwitch_pack_default_value(self, pack_data, pack_error)

    def do_check_match_switch(self, other):
        return _dcparser.DCSwitch_do_check_match_switch(self, other)

# Register DCSwitch in _dcparser:
_dcparser.DCSwitch_swigregister(DCSwitch)

class DCTypedef(DCDeclaration):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _dcparser.DCTypedef_swiginit(self, _dcparser.new_DCTypedef(*args))
    __swig_destroy__ = _dcparser.delete_DCTypedef

    def get_number(self):
        return _dcparser.DCTypedef_get_number(self)

    def get_name(self):
        return _dcparser.DCTypedef_get_name(self)

    def get_description(self):
        return _dcparser.DCTypedef_get_description(self)

    def is_bogus_typedef(self):
        return _dcparser.DCTypedef_is_bogus_typedef(self)

    def is_implicit_typedef(self):
        return _dcparser.DCTypedef_is_implicit_typedef(self)

    def make_new_parameter(self):
        return _dcparser.DCTypedef_make_new_parameter(self)

    def set_number(self, number):
        return _dcparser.DCTypedef_set_number(self, number)

    def output(self, out, brief):
        return _dcparser.DCTypedef_output(self, out, brief)

    def write(self, out, brief, indent_level):
        return _dcparser.DCTypedef_write(self, out, brief, indent_level)

# Register DCTypedef in _dcparser:
_dcparser.DCTypedef_swigregister(DCTypedef)



